-- MySQL Script generated by MySQL Workbench
-- lun. 08 mars 2021 11:33:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`center`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`center` ;

CREATE TABLE IF NOT EXISTS `mydb`.`center` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `id_type` INT NOT NULL,
  `id_center` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password_hash` CHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_type_idx` (`id_type` ASC) VISIBLE,
  INDEX `fk_user_center_idx` (`id_center` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  CONSTRAINT `fk_user_type`
    FOREIGN KEY (`id_type`)
    REFERENCES `mydb`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_center`
    FOREIGN KEY (`id_center`)
    REFERENCES `mydb`.`center` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `activity_sector` VARCHAR(45) NOT NULL,
  `interns_number` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`offer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`offer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`offer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_company` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `competences` VARCHAR(90) NOT NULL,
  `date` DATE NOT NULL,
  `duration` TIME NOT NULL,
  `remuneration` FLOAT NOT NULL,
  `slots` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_offer_company_idx` (`id_company` ASC) VISIBLE,
  CONSTRAINT `fk_offer_company`
    FOREIGN KEY (`id_company`)
    REFERENCES `mydb`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`promo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`promo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`promo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` DATE NOT NULL,
  `speciality` VARCHAR(45) NOT NULL,
  `id_center` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_promo_center_idx` (`id_center` ASC) VISIBLE,
  CONSTRAINT `fk_promo_center`
    FOREIGN KEY (`id_center`)
    REFERENCES `mydb`.`center` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`promo_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`promo_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`promo_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_promo` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_promo_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_promo_promo_idx` (`id_promo` ASC) VISIBLE,
  CONSTRAINT `fk_promo_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promo_promo`
    FOREIGN KEY (`id_promo`)
    REFERENCES `mydb`.`promo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`notation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`notation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_company` INT NOT NULL,
  `id_user` INT NOT NULL,
  `grade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notation_company_idx` (`id_company` ASC) VISIBLE,
  INDEX `fk_notation_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_notation_company`
    FOREIGN KEY (`id_company`)
    REFERENCES `mydb`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notation_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wishlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`wishlist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`wishlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_offer` INT NOT NULL,
  `state` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wishlist_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_wishlist_offer_idx` (`id_offer` ASC) VISIBLE,
  CONSTRAINT `fk_wishlist_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wishlist_offer`
    FOREIGN KEY (`id_offer`)
    REFERENCES `mydb`.`offer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`offer_promo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`offer_promo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`offer_promo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_promo` INT NOT NULL,
  `id_offer` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_offer_idx` (`id_offer` ASC) VISIBLE,
  INDEX `fk_promo_idx` (`id_promo` ASC) VISIBLE,
  CONSTRAINT `fk_offer`
    FOREIGN KEY (`id_offer`)
    REFERENCES `mydb`.`offer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promo`
    FOREIGN KEY (`id_promo`)
    REFERENCES `mydb`.`promo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`permission` ;

CREATE TABLE IF NOT EXISTS `mydb`.`permission` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permission_custom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`permission_custom` ;

CREATE TABLE IF NOT EXISTS `mydb`.`permission_custom` (
  `id_permission` INT NOT NULL,
  `id_user` INT NOT NULL,
  INDEX `fk_permission_delegue_perm_idx` (`id_permission` ASC) VISIBLE,
  INDEX `fk_permission_delegue_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_permission_delegue_perm`
    FOREIGN KEY (`id_permission`)
    REFERENCES `mydb`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permission_delegue_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permission_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`permission_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`permission_type` (
  `id_type` INT NOT NULL,
  `id_permission` INT NOT NULL,
  INDEX `fk_permission_type_permission_idx` (`id_permission` ASC) VISIBLE,
  CONSTRAINT `fk_permission_type_type`
    FOREIGN KEY (`id_type`)
    REFERENCES `mydb`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permission_type_permission`
    FOREIGN KEY (`id_permission`)
    REFERENCES `mydb`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
